spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:${SPRING_DATASOURCE_URL:postgresql://localhost:5432/javablog?serverTimezone=UTC}
    username: ${SPRING_DATASOURCE_USERNAME:snet}
    password: ${SPRING_DATASOURCE_PASSWORD:snet}
  mail:
    protocol: smtps
    host: smtp.gmail.com
    port: 465
    username: JavaESBBlog@gmail.com
    password: Blog!23$567New

mail:
  debug: true
  smtp:
    auth: true
    starttls:
      enable: true

server:
  port: ${PORT:9090}

#JWT Configuration
security:
  jwt:
    url-authentication: /api/auth/login
    authorization-header-name: Authorization
    prefix: Bearer
    secret: JWTSecretKeyForBlogBackend092020
    token-expiration-day: 10 #864000000 #10 дней
    password-level-security: 12

#Local storage
file-storage:
  type: cloud
  temp-location: tmp_storage
  relative-path:
    post: upload
    avatar: avatar
  depth: 3

#Cloudinary
cloudinary:
  url-resources: https://res.cloudinary.com/
  cloud-name: javaesbblog
  apikey: 744122468562629
  api-secret: hRn5ibp8VBRg6V4y3V9U7OTF0HM
  upload-image-url: /image/upload

#BlogInfo
blog:
  url: ${BLOGURL:http://localhost:9090}
  info:
    title: Блог интеграции
    subtitle: Общая информация
    copyright: Андрей Казаков
    copyrightFrom: 2020
    contact:
      phone: +7 921 365-44-06
      email: fyrklod@gmail.ru