spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:${SPRING_DATASOURCE_URL:postgresql://localhost:5432/javablog}
    username: ${SPRING_DATASOURCE_USERNAME:snet}
    password: ${SPRING_DATASOURCE_PASSWORD:snet}

server:
  port: ${PORT:9090}

security:
  jwt:
    url-authentication: /api/auth/login
    header: Authorization
    prefix: Bearer
    secret: JWTSecretKeyForBlogBackend092020
    expiration: 864000000 #10 дней

blog:
  info:
    title: Блог интеграции
    subtitle: Общая информация
    copyright: Андрей Казаков
    copyrightFrom: 2020
    contact:
      phone: +7 903 666-44-55
      email: mail@mail.ru