spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/javablog
    username: snet
    password: snet

blog:
  info:
    title: Блог интеграции
    subtitle: Общая информация
    copyright: Андрей Казаков
    copyrightFrom: 2020
    contact:
      phone: +7 903 666-44-55
      email: mail@mail.ru