spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:${SPRING_DATASOURCE_URL:postgresql://localhost:5432/javablog?serverTimezone=UTC}
    username: ${SPRING_DATASOURCE_USERNAME:snet}
    password: ${SPRING_DATASOURCE_PASSWORD:snet}
  mail:
    protocol: smtps
    host: smtp.gmail.com
    port: 465
    username: ${BLOG_EMAIL_USERNAME:BLOG_EMAIL_USERNAME}
    password: ${BLOG_EMAIL_PASSWORD:BLOG_EMAIL_PASSWORD}

mail:
  debug: true
  smtp:
    auth: true
    starttls:
      enable: true

server:
  port: ${PORT:9090}

#JWT Configuration
security:
  jwt:
    url-authentication: /api/auth/login
    authorization-header-name: Authorization
    prefix: Bearer
    secret: ${JWT_SECRET_KEY:JWT_SECRET_KEY}
    token-expiration-day: ${JWT_EXPIRATION_DAY:10} #864000000 #10 дней
    password-level-security: ${JWT_PASSWORD_LEVEL:12}

#Local storage
file-storage:
  type: ${STORAGE_TYPE:cloud}
  temp-location: ${STORAGE_TEMP_LOCATION:tmp_storage}
  relative-path:
    post: upload
    avatar: avatar
  depth: 3

#Cloudinary
cloudinary:
  url-resources: ${CLOUDINARY_RESOURCE_URL:https://res.cloudinary.com/}
  cloud-name: ${CLOUDINARY_USERNAME:CLOUDINARY_USERNAME}
  apikey: ${CLOUDINARY_API_KEY:CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_SECRET_KEY:CLOUDINARY_SECRET_KEY}
  upload-image-url: /image/upload

#BlogInfo
blog:
  url: ${BLOG_URL:http://www.blogurl.ru}
  info:
    title: Блог интеграции
    subtitle: Общая информация
    copyright: Андрей Казаков
    copyrightFrom: 2020
    contact:
      phone: ${BLOG_CONTACT_PHONE:8 800 000-00-00}
      email: ${BLOG_CONTACT_EMAIL:username@mail.ru}