INSERT INTO tags(name)
	VALUES ('Message'),
	('Channel'),
	('Router'),
	('Translator'),
	('EIP'),
	('Messaging Systems'),
	('Message Construction'),
	('Message Routing'),
	('Message Transformation'),
	('Messaging Channels'),
	('Messaging Endpoints'),
	('Human'),
	('HSI'),
	('ESB'),
	('Apache'),
	('Java'),
	('ETL'),
	('SSIS'),
	('Microsoft'),
	('Integration Styles'),
	('.Net');